---
:cstr: server=xe;user=irdb;password=irdb;
:provider: System.Data.OracleClient
:setup: 
- DROP SEQUENCE "CHARACTERS_SEQ"
- DROP TABLE "CHARACTERS"
- CREATE SEQUENCE   "CHARACTERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
- |
    CREATE TABLE  "CHARACTERS" 
       (	"ID" NUMBER NOT NULL ENABLE, 
    	"CLASS" VARCHAR2(20) NOT NULL ENABLE, 
    	"SLOGAN" VARCHAR2(150), 
    	"CLEVEL" NUMBER NOT NULL ENABLE, 
    	 CONSTRAINT "CHARACTERS_PK" PRIMARY KEY ("ID") ENABLE
       )

- CREATE OR REPLACE TRIGGER  "BI_CHARACTERS" before insert on "CHARACTERS" for each row begin select "CHARACTERS_SEQ".nextval into :NEW.ID from dual; end;
- ALTER TRIGGER  "BI_CHARACTERS" ENABLE
- CREATE UNIQUE INDEX  "CHARACTERS_PK" ON  "CHARACTERS" ("ID")
- INSERT INTO "CHARACTERS" (CLASS,CLEVEL,SLOGAN) VALUES('Death Knight',80,null)
- INSERT INTO "CHARACTERS" (CLASS,CLEVEL,SLOGAN) VALUES('Shaman',68,'ZAPP!')
